#!/usr/bin/env python

"""
GFA files created by MBG have float values in the FC field
This script replaces "FC:f:" with "FC:i:" (float to integer)
(to avoid issues with gfapy)
"""

import argparse
import os
import sys

from utils.log import print_message

# For gfa file created by MBG, convert FC:f: to FC:i: (float to integer)
def preprocess_gfa(input_gfa_file, output_gfa_file):
    if os.path.exists(output_gfa_file):
        raise FileExistsError(output_gfa_file + " already exists")
    else:
        fo = open(output_gfa_file, "w")

        with open(input_gfa_file, "r") as f:
            for line in f:
                data = line.strip().split()
                if data[0] == "S":
                    for i in range(len(data)):
                        if data[i].startswith("FC:f:"):
                            value = str(round(float(data[i].split(":")[-1])))
                            data[i] = "FC:i:" + value
                    fo.write("\t".join(data) + "\n")
                else:
                    fo.write("\t".join(data) + "\n")
        fo.close()

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description = "preprocess_mbg_gfa.py preprocessed gfa file generated by MBG")

    parser.add_argument("-i", "--input", type=str, help="Input GFA file", required=True)
    parser.add_argument("-o", "--output", type=str, help="Output GFA file", required=True)

    args = parser.parse_args()

    print_message("User provided arguments:", sys.argv)
    print_message("Parsed arguments:", vars(args))

    input_graph_file = args.input
    output_graph_file = args.output

    preprocess_gfa(input_graph_file, output_graph_file)
    print_message("Done")
